name: synthetic_tests_one_file_vs_many
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0


# Add regular dependencies here.
dependencies:
  args: ^2.0.0
  path: ^1.8.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

